### ISSUE TITLE
Load and process site configuration

### ISSUE THREAD

**Issue by ethnt** [ethnt/hinoki#1]
The configuration will probably be a YAML file that looks like this:

```yaml
name: Vandelay Industries
domain: vandelay.industries
source: .
destination: ./_dest/
```

Or, possibly a `config.exs` file:

```elixir
%{
  name: "Vandelay Industries",
  domain: "vandelay.industries",
  source: ".",
  destination: "./_dest"
}
```

Or maybe a struct:

```elixir
%Hinoki.Configuration{
  name: "Vandelay Industries",
  domain: "vandelay.industries",
  source: ".",
  destination: "./_dest"
}
```
